"""
Author: Parashar Bhatt

Guessing game : 

Count number of chance you take to locate correct number  generated randomly between given(input ) range of integers.
The code implements python OOP concepts.

"""



from random import  randint
#from IPython.display import clear_output

class Guess():
    def __init__(self, min_range=0, max_range=100):
        ''' constructor for Guess class
            Requires optional two parameters

            Range validation is done for actual parameter
            therefore omitting here.        
        '''
        self.min_range=min_range
        self.max_range=max_range
        self.selected_num = self.gen_num()
        self.my_input = min_range - 1

    def gen_num(self):
        ''' It generates and return 
            random integer number between given range 
        '''
        return randint(self.min_range, self.max_range)

    def disp_selected_num(self):
        ''' Displays random number selected by application. '''
        print((f"App randomly selected number is : {self.selected_num}"))
    
    def get_valid_num(self):
        ''' 
            This method allows user input their guess for random number 
            generated by application.
            responds user with appropriate messages.
        '''
        input_correct = False
        while not input_correct:
            try:
                input_num = input(f"Enter number in range {self.min_range} and {self.max_range} :")
                input_num = int(input_num)
                print(f" You entered {input_num}")
                if ((input_num >= self.min_range) and (input_num <= self.max_range)):
                    print(f"Your input is in range {self.min_range} and {self.max_range} ")
                    input_correct = True    
                else:
                    print(f"Your number {input_num} is out of range {self.min_range} and {self.max_range} ")
                    
            except:
                    print("Invalid input")

            if input_correct:
                print("valid return ")
                return input_num
            else:
                print( "Error.....")


    def compare_input(self):
        '''
            This method compares input entered by user with application
            generated random number and return boolean result of comparison.
        '''
        if self.my_input < self.selected_num:
            print("Your guess is lower than selected number")
            return False
        elif self.my_input > self.selected_num:
            print("Your guess is greater than selected number")
            return False
        else:
            print("You correctly guessed this time, Congrats...")
            return True

    def play_guess(self):
        guess_count=0
        ret_val=False
        while not ret_val :
            self.my_input = self.get_valid_num()
            ret_val = self.compare_input()
            guess_count += 1
        print(f"You took {guess_count} chances to correctly guess !!")
        self.disp_selected_num()

if __name__=='__main__':
    try:
        lr = input("Enter lower range number:")
        lr= int(lr)
        ur = input("Enter lower range number:")
        ur=int(ur)
        if lr < ur:
            g=Guess(lr,ur)
            g.play_guess()
        else:
            print('Invalid lower and upper range')
    except :
        print("custom Error  "  )

